apiVersion: v1
kind: Namespace
metadata:
  name: base-ns
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: public-gateway
  namespace: base-ns
  labels:
    gateway: public-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*.mydns.com"
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: private-gateway
  namespace: base-ns
spec:
  selector:
    custom: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "mydns-dev.com"


